### ISSUE TITLE
Display driver crashing for no reason

### ISSUE THREAD

**Issue by abnermora59** [horde-sandcastle/ChivAdmin#1]
whenever i press any button, example: settings, my pc freezes and my display driver crashes.
graphics card: AMD Radeon HD 6630M and Intel HD Graphics 3000

**Comment by opele** [comment]
But the application starts up normally? 
Do you have similar problems with other Java 8 desktop applications?
What version of JRE do you have installed?
Is there any error log?
What operating system are you using?

**Comment by abnermora59** [comment]
Yes, it starts.
No, I don't think I have any other jar.
Java 8 build 111, however, i've been using with no success Java 8 build 31 until I uninstalled it yesterday and tried this new build.
No, my screen just freezes then my display adapter crashes, leaving an error message and blank app windows.
Windows 7 64-bits

**Comment by opele** [comment]
Can you retry after updating your video card drivers?

The application stores it's settings in a file right next to the jar. Make sure the application has write permissions in the specific folder you placed the jar. Subfolders on desktop should be fine, but check the folder settings by rightclicking on it.
You may also rightclick on the jar and start it as administrator to check if it still crashes your display driver.

Also you can download an example jar using similar technologies here:
http://www.oracle.com/technetwork/java/javase/overview/javafx-samples-2158687.html
Does it also crash your pc if you run this sample app?

**Comment by abnermora59** [comment]
Now it's working! thanks
